DECLARE
 CUR SYS_REFCURSOR;
 BEGIN
 OPEN CUR FOR
 SELECT VALUE(P) FROM TABLE (DBMS_SQLTUNE.SELECT_CURSOR_CACHE('sql_id = ''&1''')) p;
 DBMS_SQLTUNE.LOAD_SQLSET(SQLSET_NAME=> '&2', POPULATE_CURSOR=>CUR);
 CLOSE CUR;
 END;
 /
