SET PAGES 10000 LINES 200
COL PARS_USER FOR A20
COL inst_id FOR 9999
COL TIME_SEC FOR 9999999
COL SQL_TEXT FOR A30
COL SQL_PROFILE FOR A30
COL SQL_PLAN_BASELINE FOR A30
COL EXECS FOR 9999
col LAST_LOAD_TIME for a25
col SQL_PROFILE for a20
col SQL_ID for a15
SELECT inst_id, SQL_ID, substr(SQL_TEXT,1,30) sql_text, LAST_LOAD_TIME, PLAN_HASH_VALUE, PARSING_SCHEMA_NAME PARS_USER, SQL_PROFILE, SQL_PLAN_BASELINE, ELAPSED_TIME, EXECUTIONS EXECS FROM GV$SQL WHERE UPPER(SQL_ID) = UPPER('&1') ORDER BY ELAPSED_TIME DESC
/
