SET PAGES 10000 LINES 200
COL PARS_USER FOR A10
COL INST FOR 9999
COL TIME_SEC FOR 9999999
COL SQL_TEXT FOR A30
COL END_INTERVAL_TIME FOR A28
COL SQL_PROFILE FOR A30
COL EXECS FOR 9999
col SQL_ID for a13
SELECT STAT.INSTANCE_NUMBER INST, STAT.SNAP_ID, SS.END_INTERVAL_TIME, STAT.SQL_ID, DBMS_LOB.SUBSTR(SQL_TEXT,30,1) SQL_TEXT, PLAN_HASH_VALUE, STAT.PARSING_SCHEMA_NAME PARS_USER,STAT.SQL_PROFILE, TRUNC(STAT.ELAPSED_TIME_DELTA/100000) TIME_SEC, EXECUTIONS_DELTA EXECS
FROM DBA_HIST_SQLSTAT STAT, DBA_HIST_SQLTEXT TXT, DBA_HIST_SNAPSHOT SS
WHERE STAT.SQL_ID = TXT.SQL_ID AND STAT.DBID = TXT.DBID AND SS.DBID = STAT.DBID AND SS.INSTANCE_NUMBER = STAT.INSTANCE_NUMBER AND STAT.SNAP_ID = SS.SNAP_ID AND SS.BEGIN_INTERVAL_TIME >= SYSDATE-90 AND UPPER(STAT.SQL_ID) = UPPER('&1') ORDER BY 3
/
